### ISSUE TITLE
Add "typed" transformers (create .d.ts files for CSS/Sass/Less/Stylus files)

### ISSUE THREAD

**Issue by kristerkari** [kristerkari/react-native-css-modules#16]
**Todo:**

- [x] Add typed CSS transformer - https://github.com/kristerkari/react-native-typed-css-transformer
- [x] Add typed Sass transformer - https://github.com/kristerkari/react-native-typed-sass-transformer
- [x] Add typed Less transformer - https://github.com/kristerkari/react-native-typed-less-transformer
- [x] Add typed Stylus transformer - https://github.com/kristerkari/react-native-typed-stylus-transformer
- [x] Add typed PostCSS transformer - https://github.com/kristerkari/react-native-typed-postcss-transformer
- [x] Add docs for typed transformers
